# Generated by Django 6.1.1 on 2026-10-08 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vacancy_uid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('vacancy_uid', ''), _negated=True), fields=('user', 'vacancy_uid'), name='one_application_per_vacancy'),
        ),
    ]
